/**
 *
 * @author Julia Menardi
 */
package com.mycompany.di01Tarea;

import java.awt.Window;
import javax.swing.JOptionPane;
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TituloPanel = new javax.swing.JPanel();
        tituloReservaLabel = new javax.swing.JLabel();
        datosReservaPanel = new javax.swing.JPanel();
        subtituloDatosLabel = new javax.swing.JLabel();
        FormPanel = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        tipoEventoLabel = new javax.swing.JLabel();
        numAsistentesLabel = new javax.swing.JLabel();
        tipoCocinaLabel = new javax.swing.JLabel();
        nombreApellido = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        numAsistentes = new javax.swing.JTextField();
        tipoCocina = new javax.swing.JComboBox<>();
        tipoDeEvento = new javax.swing.JComboBox<>();
        fechaReserva = new javax.swing.JSpinner();
        congresoPanel = new javax.swing.JPanel();
        numJornadasLabel = new javax.swing.JLabel();
        habitacionesLabel = new javax.swing.JLabel();
        numJornadasComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        siRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        reservarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        TituloPanel.setBackground(new java.awt.Color(30, 150, 160));
        TituloPanel.setToolTipText("tituloReserva");

        tituloReservaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloReservaLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloReservaLabel.setText("Reservas de Salón Habana");

        javax.swing.GroupLayout TituloPanelLayout = new javax.swing.GroupLayout(TituloPanel);
        TituloPanel.setLayout(TituloPanelLayout);
        TituloPanelLayout.setHorizontalGroup(
            TituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloReservaLabel)
                .addGap(362, 362, 362))
        );
        TituloPanelLayout.setVerticalGroup(
            TituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(tituloReservaLabel)
                .addContainerGap())
        );

        datosReservaPanel.setBackground(new java.awt.Color(30, 150, 160));
        datosReservaPanel.setToolTipText("reservaPanel");

        subtituloDatosLabel.setBackground(new java.awt.Color(30, 160, 150));
        subtituloDatosLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        subtituloDatosLabel.setForeground(new java.awt.Color(255, 255, 255));
        subtituloDatosLabel.setText("Datos de la reserva");

        FormPanel.setBackground(new java.awt.Color(255, 255, 255));
        FormPanel.setForeground(new java.awt.Color(30, 150, 160));
        FormPanel.setToolTipText("reservaPanel");

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(30, 150, 160));
        nombreLabel.setText("Nombre:");
        nombreLabel.setToolTipText("Nombre de la persona que reserva");

        telefonoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telefonoLabel.setForeground(new java.awt.Color(30, 150, 160));
        telefonoLabel.setText("Teléfono:");
        telefonoLabel.setToolTipText("Teléfono de contacto");

        tipoEventoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipoEventoLabel.setForeground(new java.awt.Color(30, 150, 160));
        tipoEventoLabel.setText("Tipo de evento:");
        tipoEventoLabel.setToolTipText("Tipo de evento");

        numAsistentesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numAsistentesLabel.setForeground(new java.awt.Color(30, 150, 160));
        numAsistentesLabel.setText("Nº de asistentes:");
        numAsistentesLabel.setToolTipText("Número de asistentes");

        tipoCocinaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipoCocinaLabel.setForeground(new java.awt.Color(30, 150, 160));
        tipoCocinaLabel.setText("Tipo de cocina:");
        tipoCocinaLabel.setToolTipText("Tipo de cocina");

        nombreApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreApellido.setToolTipText("nombreText");
        nombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreApellidoActionPerformed(evt);
            }
        });

        telefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefono.setToolTipText("telefonoText");

        fechaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(30, 150, 160));
        fechaLabel.setText("Fecha del evento:");
        fechaLabel.setToolTipText("Fecha del evento");

        numAsistentes.setColumns(1);
        numAsistentes.setToolTipText("numAsistentes");
        numAsistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAsistentesActionPerformed(evt);
            }
        });

        tipoCocina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoCocina.setForeground(new java.awt.Color(30, 150, 160));
        tipoCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Buffé", "Carta", "Cita con el chef", "No precisa" }));
        tipoCocina.setToolTipText("tipoCocina");

        tipoDeEvento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoDeEvento.setForeground(new java.awt.Color(30, 150, 160));
        tipoDeEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Banquete", "Jornada", "Congreso" }));
        tipoDeEvento.setToolTipText("tipoEvento");
        tipoDeEvento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoDeEventoItemStateChanged(evt);
            }
        });

        fechaReserva.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1761606000000L), java.util.Calendar.DAY_OF_MONTH));
        fechaReserva.setToolTipText("fecha del evento");

        congresoPanel.setBackground(new java.awt.Color(255, 255, 255));
        congresoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(30, 150, 160), null));
        congresoPanel.setToolTipText("Opciones congreso");
        congresoPanel.setEnabled(false);

        numJornadasLabel.setBackground(new java.awt.Color(30, 150, 160));
        numJornadasLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numJornadasLabel.setForeground(new java.awt.Color(30, 150, 160));
        numJornadasLabel.setText("Nº de Jornadas:");
        numJornadasLabel.setToolTipText("Número de jornadas del congreso");
        numJornadasLabel.setEnabled(false);

        habitacionesLabel.setBackground(new java.awt.Color(30, 150, 160));
        habitacionesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        habitacionesLabel.setForeground(new java.awt.Color(30, 150, 160));
        habitacionesLabel.setText("Requiere habitaciones:");
        habitacionesLabel.setToolTipText("requiereHabs");
        habitacionesLabel.setEnabled(false);

        numJornadasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));
        numJornadasComboBox.setToolTipText("jornadas");
        numJornadasComboBox.setEnabled(false);

        buttonGroup1.add(siRadioButton);
        siRadioButton.setText("Sí");
        siRadioButton.setToolTipText("siHabitacion");
        siRadioButton.setEnabled(false);
        siRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(noRadioButton);
        noRadioButton.setText("No");
        noRadioButton.setToolTipText("noHabitacion");
        noRadioButton.setEnabled(false);

        javax.swing.GroupLayout congresoPanelLayout = new javax.swing.GroupLayout(congresoPanel);
        congresoPanel.setLayout(congresoPanelLayout);
        congresoPanelLayout.setHorizontalGroup(
            congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congresoPanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitacionesLabel)
                    .addGroup(congresoPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(numJornadasLabel)))
                .addGap(1, 1, 1)
                .addGroup(congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(congresoPanelLayout.createSequentialGroup()
                        .addComponent(siRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noRadioButton))
                    .addComponent(numJornadasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        congresoPanelLayout.setVerticalGroup(
            congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congresoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numJornadasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numJornadasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitacionesLabel)
                    .addComponent(siRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noRadioButton))
                .addContainerGap())
        );

        reservarButton.setBackground(new java.awt.Color(30, 150, 160));
        reservarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reservarButton.setForeground(new java.awt.Color(255, 255, 255));
        reservarButton.setText("Reservar");
        reservarButton.setToolTipText("reservarButton");
        reservarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormPanelLayout = new javax.swing.GroupLayout(FormPanel);
        FormPanel.setLayout(FormPanelLayout);
        FormPanelLayout.setHorizontalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addComponent(reservarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPanelLayout.createSequentialGroup()
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPanelLayout.createSequentialGroup()
                                .addComponent(tipoCocinaLabel)
                                .addGap(25, 25, 25))
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel)
                                    .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fechaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(telefonoLabel))
                                    .addComponent(tipoEventoLabel)
                                    .addComponent(numAsistentesLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoDeEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(telefono)
                            .addComponent(nombreApellido)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(congresoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))))
        );
        FormPanelLayout.setVerticalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoLabel))
                        .addGap(8, 8, 8)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tipoDeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoEventoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numAsistentes, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(numAsistentesLabel))))
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(congresoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoCocinaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoCocina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        congresoPanel.getAccessibleContext().setAccessibleParent(null);

        javax.swing.GroupLayout datosReservaPanelLayout = new javax.swing.GroupLayout(datosReservaPanel);
        datosReservaPanel.setLayout(datosReservaPanelLayout);
        datosReservaPanelLayout.setHorizontalGroup(
            datosReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosReservaPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(datosReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosReservaPanelLayout.createSequentialGroup()
                        .addComponent(FormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosReservaPanelLayout.createSequentialGroup()
                        .addComponent(subtituloDatosLabel)
                        .addGap(403, 403, 403))))
        );
        datosReservaPanelLayout.setVerticalGroup(
            datosReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosReservaPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(subtituloDatosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(datosReservaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosReservaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Función que habilita y deshabilita los componentes correspondientes a "Congreso"
     * @param args the command line arguments
     * @author Julia Menardi
     */
    private void tipoDeEventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoDeEventoItemStateChanged
        String tipoEvento = (String) tipoDeEvento.getSelectedItem();
        if(tipoEvento.equals("Congreso")){
            numJornadasComboBox.setEnabled(true);
            siRadioButton.setEnabled(true);
            noRadioButton.setEnabled(true);
            habitacionesLabel.setEnabled(true);
            numJornadasLabel.setEnabled(true);
        } else {
            numJornadasComboBox.setEnabled(false);
            siRadioButton.setEnabled(false);
            noRadioButton.setEnabled(false);
            habitacionesLabel.setEnabled(false);
            numJornadasLabel.setEnabled(false);
        }
    }//GEN-LAST:event_tipoDeEventoItemStateChanged

    private void numAsistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAsistentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numAsistentesActionPerformed

    private void nombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreApellidoActionPerformed

    private void siRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siRadioButtonActionPerformed

    /**
     * Función que comprueba que no haya campos vacíos y muestra el aviso correspondiente
     * @param args the command line arguments
     * @author Julia Menardi
     */
    private void reservarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarButtonActionPerformed
        
        if(nombreApellido.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe completarse el nombre y apellido", "Falta un dato", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(telefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe completarse el teléfono", "Falta un dato", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(telefono.getText().isEmpty() || !telefono.getText().matches("\\d{9}")){
            JOptionPane.showMessageDialog(this, "Debe completarse con un teléfono válido", "Falta un dato", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if(tipoDeEvento.getSelectedItem() == "Seleccionar"){
            JOptionPane.showMessageDialog(this, "Debe completarse el tipo de evento", "Falta un dato", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(tipoDeEvento.getSelectedItem() == "Congreso"){
            if(numJornadasComboBox.getSelectedItem() == "0" || (!siRadioButton.isSelected() && !noRadioButton.isSelected())){
            JOptionPane.showMessageDialog(this, "Deben completarse los campos correspondientes a congreso", "Falta un dato", JOptionPane.INFORMATION_MESSAGE);
            return;
            }
        }  
        
        if(numAsistentes.getText().isEmpty() || !numAsistentes.getText().matches("\\d{1,3}")){
            JOptionPane.showMessageDialog(this, "Debe completarse con un número de asistentes válido", "Falta un dato", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(tipoCocina.getSelectedItem() == "Seleccionar"){
            JOptionPane.showMessageDialog(this, "Debe completarse el tipo de cocina", "Falta un dato", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Reserva guardada con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        
        // Pregunta si quiere realizar otra reserva
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea realizar otra reserva en el mismo salón?", "Confirmación", JOptionPane.YES_NO_OPTION);
    
        if (respuesta == JOptionPane.YES_OPTION) {
            limpiarForm();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_reservarButtonActionPerformed

    /**
     * Función que reestablece los campos del formulario
     * @param args the command line arguments
     * @author Julia Menardi
     */
    private void limpiarForm(){
        nombreApellido.setText("");
        telefono.setText("");
        numAsistentes.setText("");
        tipoDeEvento.setSelectedItem("Seleccionar");        
        tipoCocina.setSelectedItem("Seleccionar");
        numJornadasComboBox.setSelectedItem("0");
        fechaReserva.setValue(new java.util.Date());
        buttonGroup1.clearSelection(); 
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormPanel;
    private javax.swing.JPanel TituloPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel congresoPanel;
    private javax.swing.JPanel datosReservaPanel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JSpinner fechaReserva;
    private javax.swing.JLabel habitacionesLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JTextField nombreApellido;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField numAsistentes;
    private javax.swing.JLabel numAsistentesLabel;
    private javax.swing.JComboBox<String> numJornadasComboBox;
    private javax.swing.JLabel numJornadasLabel;
    private javax.swing.JButton reservarButton;
    private javax.swing.JRadioButton siRadioButton;
    private javax.swing.JLabel subtituloDatosLabel;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JComboBox<String> tipoCocina;
    private javax.swing.JLabel tipoCocinaLabel;
    private javax.swing.JComboBox<String> tipoDeEvento;
    private javax.swing.JLabel tipoEventoLabel;
    private javax.swing.JLabel tituloReservaLabel;
    // End of variables declaration//GEN-END:variables
}
