/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.di01Tarea;

/**
 *
 * @author super
 */
public class GestionHotelera extends javax.swing.JFrame {

    /**
     * Creates new 
     */
    public GestionHotelera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormPanel = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        tipoEventoLabel = new javax.swing.JLabel();
        numAsistentesLabel = new javax.swing.JLabel();
        tipoCocinaLabel = new javax.swing.JLabel();
        nombreApellido = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        numAsistentes = new javax.swing.JTextField();
        tipoCocina = new javax.swing.JComboBox<>();
        tipoDeEvento = new javax.swing.JComboBox<>();
        fechaReserva = new javax.swing.JSpinner();
        congresoPanel = new javax.swing.JPanel();
        numJornadasLabel = new javax.swing.JLabel();
        habitacionesLabel = new javax.swing.JLabel();
        numJornadasComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        siRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        jFrame1 = new javax.swing.JFrame();
        TituloPanel = new javax.swing.JPanel();
        tituloReservaLabel = new javax.swing.JLabel();
        datosReservaPanel = new javax.swing.JPanel();
        subtituloDatosLabel = new javax.swing.JLabel();
        FormPanel1 = new javax.swing.JPanel();
        nombreLabel1 = new javax.swing.JLabel();
        telefonoLabel1 = new javax.swing.JLabel();
        tipoEventoLabel1 = new javax.swing.JLabel();
        numAsistentesLabel1 = new javax.swing.JLabel();
        tipoCocinaLabel1 = new javax.swing.JLabel();
        nombreApellido1 = new javax.swing.JTextField();
        telefono1 = new javax.swing.JTextField();
        fechaLabel1 = new javax.swing.JLabel();
        numAsistentes1 = new javax.swing.JTextField();
        tipoCocina1 = new javax.swing.JComboBox<>();
        tipoDeEvento1 = new javax.swing.JComboBox<>();
        fechaReserva1 = new javax.swing.JSpinner();
        congresoPanel1 = new javax.swing.JPanel();
        numJornadasLabel1 = new javax.swing.JLabel();
        habitacionesLabel1 = new javax.swing.JLabel();
        numJornadasComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        siRadioButton1 = new javax.swing.JRadioButton();
        noRadioButton1 = new javax.swing.JRadioButton();
        aceptarButton = new javax.swing.JButton();
        FormPanel2 = new javax.swing.JPanel();
        nombreLabel2 = new javax.swing.JLabel();
        telefonoLabel2 = new javax.swing.JLabel();
        tipoEventoLabel2 = new javax.swing.JLabel();
        numAsistentesLabel2 = new javax.swing.JLabel();
        tipoCocinaLabel2 = new javax.swing.JLabel();
        nombreApellido2 = new javax.swing.JTextField();
        telefono2 = new javax.swing.JTextField();
        fechaLabel2 = new javax.swing.JLabel();
        numAsistentes2 = new javax.swing.JTextField();
        tipoCocina2 = new javax.swing.JComboBox<>();
        tipoDeEvento2 = new javax.swing.JComboBox<>();
        fechaReserva2 = new javax.swing.JSpinner();
        congresoPanel2 = new javax.swing.JPanel();
        numJornadasLabel2 = new javax.swing.JLabel();
        habitacionesLabel2 = new javax.swing.JLabel();
        numJornadasComboBox2 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        siRadioButton2 = new javax.swing.JRadioButton();
        noRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        tituloPrincipalPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seleccionarSalonPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        gestionarReservaButton = new javax.swing.JButton();
        seleccionarLabel = new javax.swing.JLabel();
        seleccionarSalon = new javax.swing.JComboBox<>();

        FormPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102)));

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(30, 150, 160));
        nombreLabel.setText("Nombre:");
        nombreLabel.setToolTipText("Nombre de la persona que reserva");

        telefonoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefonoLabel.setForeground(new java.awt.Color(30, 150, 160));
        telefonoLabel.setText("Teléfono:");
        telefonoLabel.setToolTipText("Teléfono de contacto");

        tipoEventoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoEventoLabel.setForeground(new java.awt.Color(30, 150, 160));
        tipoEventoLabel.setText("Tipo de evento:");
        tipoEventoLabel.setToolTipText("Tipo de evento");

        numAsistentesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numAsistentesLabel.setForeground(new java.awt.Color(30, 150, 160));
        numAsistentesLabel.setText("Nº de asistentes:");
        numAsistentesLabel.setToolTipText("Número de asistentes");

        tipoCocinaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoCocinaLabel.setForeground(new java.awt.Color(30, 150, 160));
        tipoCocinaLabel.setText("Tipo de cocina:");
        tipoCocinaLabel.setToolTipText("Tipo de cocina");

        nombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreApellidoActionPerformed(evt);
            }
        });

        fechaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(30, 150, 160));
        fechaLabel.setText("Fecha del evento:");
        fechaLabel.setToolTipText("Fecha del evento");

        numAsistentes.setColumns(1);
        numAsistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAsistentesActionPerformed(evt);
            }
        });

        tipoCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buffé", "Carta", "Cita con el chef", "No precisa" }));

        tipoDeEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        tipoDeEvento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoDeEventoItemStateChanged(evt);
            }
        });

        fechaReserva.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1761606000000L), java.util.Calendar.DAY_OF_MONTH));
        fechaReserva.setToolTipText("fecha del evento");

        congresoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        congresoPanel.setToolTipText("Opciones congreso");
        congresoPanel.setEnabled(false);

        numJornadasLabel.setBackground(new java.awt.Color(30, 150, 160));
        numJornadasLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numJornadasLabel.setForeground(new java.awt.Color(30, 150, 160));
        numJornadasLabel.setText("Número de Jornadas:");
        numJornadasLabel.setToolTipText("Número de jornadas del congreso");
        numJornadasLabel.setEnabled(false);

        habitacionesLabel.setBackground(new java.awt.Color(30, 150, 160));
        habitacionesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        habitacionesLabel.setForeground(new java.awt.Color(30, 150, 160));
        habitacionesLabel.setText("Requiere habitaciones:");
        habitacionesLabel.setToolTipText("Teléfono de contacto");
        habitacionesLabel.setEnabled(false);

        numJornadasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));
        numJornadasComboBox.setToolTipText("jornadas");
        numJornadasComboBox.setEnabled(false);

        siRadioButton.setText("Sí");
        siRadioButton.setToolTipText("siHabitacion");
        siRadioButton.setEnabled(false);
        siRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setText("No");
        noRadioButton.setToolTipText("noHabitacion");
        noRadioButton.setEnabled(false);

        javax.swing.GroupLayout congresoPanelLayout = new javax.swing.GroupLayout(congresoPanel);
        congresoPanel.setLayout(congresoPanelLayout);
        congresoPanelLayout.setHorizontalGroup(
            congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congresoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(congresoPanelLayout.createSequentialGroup()
                        .addComponent(habitacionesLabel)
                        .addGap(1, 1, 1)
                        .addComponent(siRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noRadioButton))
                    .addGroup(congresoPanelLayout.createSequentialGroup()
                        .addComponent(numJornadasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numJornadasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        congresoPanelLayout.setVerticalGroup(
            congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congresoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numJornadasLabel)
                    .addComponent(numJornadasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(congresoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitacionesLabel)
                    .addComponent(siRadioButton)
                    .addComponent(noRadioButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout FormPanelLayout = new javax.swing.GroupLayout(FormPanel);
        FormPanel.setLayout(FormPanelLayout);
        FormPanelLayout.setHorizontalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaLabel)
                            .addComponent(telefonoLabel)
                            .addComponent(nombreLabel)
                            .addComponent(tipoEventoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoDeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addComponent(congresoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addComponent(tipoCocinaLabel)
                                .addGap(8, 8, 8))
                            .addComponent(numAsistentesLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(numAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        FormPanelLayout.setVerticalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(fechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tipoDeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoEventoLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numAsistentesLabel)
                            .addComponent(numAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoCocinaLabel)
                            .addComponent(tipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(congresoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloPanel.setBackground(new java.awt.Color(30, 150, 160));

        tituloReservaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloReservaLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloReservaLabel.setText("Reservas de Salón Habana");

        javax.swing.GroupLayout TituloPanelLayout = new javax.swing.GroupLayout(TituloPanel);
        TituloPanel.setLayout(TituloPanelLayout);
        TituloPanelLayout.setHorizontalGroup(
            TituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloPanelLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(tituloReservaLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TituloPanelLayout.setVerticalGroup(
            TituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloReservaLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        datosReservaPanel.setBackground(new java.awt.Color(30, 150, 160));

        subtituloDatosLabel.setBackground(new java.awt.Color(30, 160, 150));
        subtituloDatosLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtituloDatosLabel.setForeground(new java.awt.Color(255, 255, 255));
        subtituloDatosLabel.setText("Datos de la reserva");

        FormPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102)));

        nombreLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreLabel1.setForeground(new java.awt.Color(30, 150, 160));
        nombreLabel1.setText("Nombre:");
        nombreLabel1.setToolTipText("Nombre de la persona que reserva");

        telefonoLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefonoLabel1.setForeground(new java.awt.Color(30, 150, 160));
        telefonoLabel1.setText("Teléfono:");
        telefonoLabel1.setToolTipText("Teléfono de contacto");

        tipoEventoLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoEventoLabel1.setForeground(new java.awt.Color(30, 150, 160));
        tipoEventoLabel1.setText("Tipo de evento:");
        tipoEventoLabel1.setToolTipText("Tipo de evento");

        numAsistentesLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numAsistentesLabel1.setForeground(new java.awt.Color(30, 150, 160));
        numAsistentesLabel1.setText("Nº de asistentes:");
        numAsistentesLabel1.setToolTipText("Número de asistentes");

        tipoCocinaLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoCocinaLabel1.setForeground(new java.awt.Color(30, 150, 160));
        tipoCocinaLabel1.setText("Tipo de cocina:");
        tipoCocinaLabel1.setToolTipText("Tipo de cocina");

        nombreApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreApellido1ActionPerformed(evt);
            }
        });

        fechaLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaLabel1.setForeground(new java.awt.Color(30, 150, 160));
        fechaLabel1.setText("Fecha del evento:");
        fechaLabel1.setToolTipText("Fecha del evento");

        numAsistentes1.setColumns(1);
        numAsistentes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAsistentes1ActionPerformed(evt);
            }
        });

        tipoCocina1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buffé", "Carta", "Cita con el chef", "No precisa" }));

        tipoDeEvento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        tipoDeEvento1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoDeEvento1ItemStateChanged(evt);
            }
        });

        fechaReserva1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1761606000000L), java.util.Calendar.DAY_OF_MONTH));
        fechaReserva1.setToolTipText("fecha del evento");

        congresoPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        congresoPanel1.setToolTipText("Opciones congreso");
        congresoPanel1.setEnabled(false);

        numJornadasLabel1.setBackground(new java.awt.Color(30, 150, 160));
        numJornadasLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numJornadasLabel1.setForeground(new java.awt.Color(30, 150, 160));
        numJornadasLabel1.setText("Número de Jornadas:");
        numJornadasLabel1.setToolTipText("Número de jornadas del congreso");
        numJornadasLabel1.setEnabled(false);

        habitacionesLabel1.setBackground(new java.awt.Color(30, 150, 160));
        habitacionesLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        habitacionesLabel1.setForeground(new java.awt.Color(30, 150, 160));
        habitacionesLabel1.setText("Requiere habitaciones:");
        habitacionesLabel1.setToolTipText("Teléfono de contacto");
        habitacionesLabel1.setEnabled(false);

        numJornadasComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));
        numJornadasComboBox1.setToolTipText("jornadas");
        numJornadasComboBox1.setEnabled(false);

        siRadioButton1.setText("Sí");
        siRadioButton1.setToolTipText("siHabitacion");
        siRadioButton1.setEnabled(false);
        siRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siRadioButton1ActionPerformed(evt);
            }
        });

        noRadioButton1.setText("No");
        noRadioButton1.setToolTipText("noHabitacion");
        noRadioButton1.setEnabled(false);

        javax.swing.GroupLayout congresoPanel1Layout = new javax.swing.GroupLayout(congresoPanel1);
        congresoPanel1.setLayout(congresoPanel1Layout);
        congresoPanel1Layout.setHorizontalGroup(
            congresoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congresoPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(congresoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(congresoPanel1Layout.createSequentialGroup()
                        .addComponent(habitacionesLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(siRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noRadioButton1))
                    .addGroup(congresoPanel1Layout.createSequentialGroup()
                        .addComponent(numJornadasLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numJornadasComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        congresoPanel1Layout.setVerticalGroup(
            congresoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congresoPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(congresoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numJornadasLabel1)
                    .addComponent(numJornadasComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(congresoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitacionesLabel1)
                    .addComponent(siRadioButton1)
                    .addComponent(noRadioButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout FormPanel1Layout = new javax.swing.GroupLayout(FormPanel1);
        FormPanel1.setLayout(FormPanel1Layout);
        FormPanel1Layout.setHorizontalGroup(
            FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanel1Layout.createSequentialGroup()
                        .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaLabel1)
                            .addComponent(telefonoLabel1)
                            .addComponent(nombreLabel1)
                            .addComponent(tipoEventoLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FormPanel1Layout.createSequentialGroup()
                                .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoDeEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaReserva1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addComponent(congresoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(FormPanel1Layout.createSequentialGroup()
                        .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanel1Layout.createSequentialGroup()
                                .addComponent(tipoCocinaLabel1)
                                .addGap(8, 8, 8))
                            .addComponent(numAsistentesLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tipoCocina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(numAsistentes1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        FormPanel1Layout.setVerticalGroup(
            FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel1)
                    .addComponent(nombreApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel1)
                    .addComponent(fechaReserva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanel1Layout.createSequentialGroup()
                        .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tipoDeEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoEventoLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numAsistentesLabel1)
                            .addComponent(numAsistentes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoCocinaLabel1)
                            .addComponent(tipoCocina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(congresoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        aceptarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aceptarButton.setForeground(new java.awt.Color(30, 150, 160));
        aceptarButton.setText("Aceptar");
        aceptarButton.setToolTipText("aceptarButton");

        javax.swing.GroupLayout datosReservaPanelLayout = new javax.swing.GroupLayout(datosReservaPanel);
        datosReservaPanel.setLayout(datosReservaPanelLayout);
        datosReservaPanelLayout.setHorizontalGroup(
            datosReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosReservaPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(FormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosReservaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(datosReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosReservaPanelLayout.createSequentialGroup()
                        .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosReservaPanelLayout.createSequentialGroup()
                        .addComponent(subtituloDatosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(362, 362, 362))))
        );
        datosReservaPanelLayout.setVerticalGroup(
            datosReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosReservaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subtituloDatosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptarButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datosReservaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(TituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosReservaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FormPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102)));

        nombreLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreLabel2.setForeground(new java.awt.Color(30, 150, 160));
        nombreLabel2.setText("Nombre:");
        nombreLabel2.setToolTipText("Nombre de la persona que reserva");

        telefonoLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefonoLabel2.setForeground(new java.awt.Color(30, 150, 160));
        telefonoLabel2.setText("Teléfono:");
        telefonoLabel2.setToolTipText("Teléfono de contacto");

        tipoEventoLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoEventoLabel2.setForeground(new java.awt.Color(30, 150, 160));
        tipoEventoLabel2.setText("Tipo de evento:");
        tipoEventoLabel2.setToolTipText("Tipo de evento");

        numAsistentesLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numAsistentesLabel2.setForeground(new java.awt.Color(30, 150, 160));
        numAsistentesLabel2.setText("Nº de asistentes:");
        numAsistentesLabel2.setToolTipText("Número de asistentes");

        tipoCocinaLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoCocinaLabel2.setForeground(new java.awt.Color(30, 150, 160));
        tipoCocinaLabel2.setText("Tipo de cocina:");
        tipoCocinaLabel2.setToolTipText("Tipo de cocina");

        nombreApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreApellido2ActionPerformed(evt);
            }
        });

        fechaLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaLabel2.setForeground(new java.awt.Color(30, 150, 160));
        fechaLabel2.setText("Fecha del evento:");
        fechaLabel2.setToolTipText("Fecha del evento");

        numAsistentes2.setColumns(1);
        numAsistentes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAsistentes2ActionPerformed(evt);
            }
        });

        tipoCocina2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buffé", "Carta", "Cita con el chef", "No precisa" }));

        tipoDeEvento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        tipoDeEvento2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoDeEvento2ItemStateChanged(evt);
            }
        });

        fechaReserva2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1761606000000L), java.util.Calendar.DAY_OF_MONTH));
        fechaReserva2.setToolTipText("fecha del evento");

        congresoPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        congresoPanel2.setToolTipText("Opciones congreso");
        congresoPanel2.setEnabled(false);

        numJornadasLabel2.setBackground(new java.awt.Color(30, 150, 160));
        numJornadasLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numJornadasLabel2.setForeground(new java.awt.Color(30, 150, 160));
        numJornadasLabel2.setText("Número de Jornadas:");
        numJornadasLabel2.setToolTipText("Número de jornadas del congreso");
        numJornadasLabel2.setEnabled(false);

        habitacionesLabel2.setBackground(new java.awt.Color(30, 150, 160));
        habitacionesLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        habitacionesLabel2.setForeground(new java.awt.Color(30, 150, 160));
        habitacionesLabel2.setText("Requiere habitaciones:");
        habitacionesLabel2.setToolTipText("Teléfono de contacto");
        habitacionesLabel2.setEnabled(false);

        numJornadasComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));
        numJornadasComboBox2.setToolTipText("jornadas");
        numJornadasComboBox2.setEnabled(false);

        siRadioButton2.setText("Sí");
        siRadioButton2.setToolTipText("siHabitacion");
        siRadioButton2.setEnabled(false);
        siRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siRadioButton2ActionPerformed(evt);
            }
        });

        noRadioButton2.setText("No");
        noRadioButton2.setToolTipText("noHabitacion");
        noRadioButton2.setEnabled(false);

        javax.swing.GroupLayout congresoPanel2Layout = new javax.swing.GroupLayout(congresoPanel2);
        congresoPanel2.setLayout(congresoPanel2Layout);
        congresoPanel2Layout.setHorizontalGroup(
            congresoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congresoPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(congresoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(congresoPanel2Layout.createSequentialGroup()
                        .addComponent(habitacionesLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(siRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noRadioButton2))
                    .addGroup(congresoPanel2Layout.createSequentialGroup()
                        .addComponent(numJornadasLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numJornadasComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        congresoPanel2Layout.setVerticalGroup(
            congresoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congresoPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(congresoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numJornadasLabel2)
                    .addComponent(numJornadasComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(congresoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitacionesLabel2)
                    .addComponent(siRadioButton2)
                    .addComponent(noRadioButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout FormPanel2Layout = new javax.swing.GroupLayout(FormPanel2);
        FormPanel2.setLayout(FormPanel2Layout);
        FormPanel2Layout.setHorizontalGroup(
            FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanel2Layout.createSequentialGroup()
                        .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaLabel2)
                            .addComponent(telefonoLabel2)
                            .addComponent(nombreLabel2)
                            .addComponent(tipoEventoLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FormPanel2Layout.createSequentialGroup()
                                .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoDeEvento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaReserva2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addComponent(congresoPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(FormPanel2Layout.createSequentialGroup()
                        .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanel2Layout.createSequentialGroup()
                                .addComponent(tipoCocinaLabel2)
                                .addGap(8, 8, 8))
                            .addComponent(numAsistentesLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tipoCocina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(numAsistentes2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        FormPanel2Layout.setVerticalGroup(
            FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel2)
                    .addComponent(nombreApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel2)
                    .addComponent(fechaReserva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanel2Layout.createSequentialGroup()
                        .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tipoDeEvento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoEventoLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numAsistentesLabel2)
                            .addComponent(numAsistentes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoCocinaLabel2)
                            .addComponent(tipoCocina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(congresoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tituloPrincipalPanel.setBackground(new java.awt.Color(30, 150, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión Hotelera");

        javax.swing.GroupLayout tituloPrincipalPanelLayout = new javax.swing.GroupLayout(tituloPrincipalPanel);
        tituloPrincipalPanel.setLayout(tituloPrincipalPanelLayout);
        tituloPrincipalPanelLayout.setHorizontalGroup(
            tituloPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPrincipalPanelLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloPrincipalPanelLayout.setVerticalGroup(
            tituloPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPrincipalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        seleccionarSalonPanel.setBackground(new java.awt.Color(30, 150, 160));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        gestionarReservaButton.setBackground(new java.awt.Color(30, 150, 160));
        gestionarReservaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gestionarReservaButton.setForeground(new java.awt.Color(255, 255, 255));
        gestionarReservaButton.setText("Gestionar reserva");
        gestionarReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarReservaButton(evt);
            }
        });

        seleccionarLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seleccionarLabel.setForeground(new java.awt.Color(30, 150, 160));
        seleccionarLabel.setText("Seleccionar Salón");
        seleccionarLabel.setToolTipText("seleccionar salon");

        seleccionarSalon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seleccionarSalon.setForeground(new java.awt.Color(30, 150, 160));
        seleccionarSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habana" }));
        seleccionarSalon.setToolTipText("seleccionar salon");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(seleccionarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gestionarReservaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(seleccionarLabel)
                .addGap(31, 31, 31)
                .addComponent(seleccionarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(gestionarReservaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout seleccionarSalonPanelLayout = new javax.swing.GroupLayout(seleccionarSalonPanel);
        seleccionarSalonPanel.setLayout(seleccionarSalonPanelLayout);
        seleccionarSalonPanelLayout.setHorizontalGroup(
            seleccionarSalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarSalonPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        seleccionarSalonPanelLayout.setVerticalGroup(
            seleccionarSalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarSalonPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionarSalonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tituloPrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tituloPrincipalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarSalonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreApellidoActionPerformed

    private void numAsistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAsistentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numAsistentesActionPerformed

    private void tipoDeEventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoDeEventoItemStateChanged
        String tipoEvento = (String) tipoDeEvento.getSelectedItem();
        if(tipoEvento.equals("Congreso")){
            numJornadasComboBox.setEnabled(true);
            siRadioButton.setEnabled(true);
            noRadioButton.setEnabled(true);
            habitacionesLabel.setEnabled(true);
            numJornadasLabel.setEnabled(true);
        } else {
            numJornadasComboBox.setEnabled(false);
            siRadioButton.setEnabled(false);
            noRadioButton.setEnabled(false);
            habitacionesLabel.setEnabled(false);
            numJornadasLabel.setEnabled(false);
        }
    }//GEN-LAST:event_tipoDeEventoItemStateChanged

    private void siRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siRadioButtonActionPerformed

    private void nombreApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreApellido1ActionPerformed

    private void numAsistentes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAsistentes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numAsistentes1ActionPerformed

    private void tipoDeEvento1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoDeEvento1ItemStateChanged
        String tipoEvento = (String) tipoDeEvento.getSelectedItem();
        if(tipoEvento.equals("Congreso")){
            numJornadasComboBox.setEnabled(true);
            siRadioButton.setEnabled(true);
            noRadioButton.setEnabled(true);
            habitacionesLabel.setEnabled(true);
            numJornadasLabel.setEnabled(true);
        } else {
            numJornadasComboBox.setEnabled(false);
            siRadioButton.setEnabled(false);
            noRadioButton.setEnabled(false);
            habitacionesLabel.setEnabled(false);
            numJornadasLabel.setEnabled(false);
        }
    }//GEN-LAST:event_tipoDeEvento1ItemStateChanged

    private void siRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siRadioButton1ActionPerformed

    private void nombreApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreApellido2ActionPerformed

    private void numAsistentes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAsistentes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numAsistentes2ActionPerformed

    private void tipoDeEvento2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoDeEvento2ItemStateChanged
        String tipoEvento = (String) tipoDeEvento.getSelectedItem();
        if(tipoEvento.equals("Congreso")){
            numJornadasComboBox.setEnabled(true);
            siRadioButton.setEnabled(true);
            noRadioButton.setEnabled(true);
            habitacionesLabel.setEnabled(true);
            numJornadasLabel.setEnabled(true);
        } else {
            numJornadasComboBox.setEnabled(false);
            siRadioButton.setEnabled(false);
            noRadioButton.setEnabled(false);
            habitacionesLabel.setEnabled(false);
            numJornadasLabel.setEnabled(false);
        }
    }//GEN-LAST:event_tipoDeEvento2ItemStateChanged

    private void siRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siRadioButton2ActionPerformed

    private void gestionarReservaButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarReservaButton
        Formulario reservaFormulario = new Formulario();
        reservaFormulario.setVisible(true);
    }//GEN-LAST:event_gestionarReservaButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionHotelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionHotelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionHotelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionHotelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionHotelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormPanel;
    private javax.swing.JPanel FormPanel1;
    private javax.swing.JPanel FormPanel2;
    private javax.swing.JPanel TituloPanel;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JPanel congresoPanel;
    private javax.swing.JPanel congresoPanel1;
    private javax.swing.JPanel congresoPanel2;
    private javax.swing.JPanel datosReservaPanel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel fechaLabel1;
    private javax.swing.JLabel fechaLabel2;
    private javax.swing.JSpinner fechaReserva;
    private javax.swing.JSpinner fechaReserva1;
    private javax.swing.JSpinner fechaReserva2;
    private javax.swing.JButton gestionarReservaButton;
    private javax.swing.JLabel habitacionesLabel;
    private javax.swing.JLabel habitacionesLabel1;
    private javax.swing.JLabel habitacionesLabel2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JRadioButton noRadioButton1;
    private javax.swing.JRadioButton noRadioButton2;
    private javax.swing.JTextField nombreApellido;
    private javax.swing.JTextField nombreApellido1;
    private javax.swing.JTextField nombreApellido2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JLabel nombreLabel2;
    private javax.swing.JTextField numAsistentes;
    private javax.swing.JTextField numAsistentes1;
    private javax.swing.JTextField numAsistentes2;
    private javax.swing.JLabel numAsistentesLabel;
    private javax.swing.JLabel numAsistentesLabel1;
    private javax.swing.JLabel numAsistentesLabel2;
    private javax.swing.JComboBox<String> numJornadasComboBox;
    private javax.swing.JComboBox<String> numJornadasComboBox1;
    private javax.swing.JComboBox<String> numJornadasComboBox2;
    private javax.swing.JLabel numJornadasLabel;
    private javax.swing.JLabel numJornadasLabel1;
    private javax.swing.JLabel numJornadasLabel2;
    private javax.swing.JLabel seleccionarLabel;
    private javax.swing.JComboBox<String> seleccionarSalon;
    private javax.swing.JPanel seleccionarSalonPanel;
    private javax.swing.JRadioButton siRadioButton;
    private javax.swing.JRadioButton siRadioButton1;
    private javax.swing.JRadioButton siRadioButton2;
    private javax.swing.JLabel subtituloDatosLabel;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel telefonoLabel1;
    private javax.swing.JLabel telefonoLabel2;
    private javax.swing.JComboBox<String> tipoCocina;
    private javax.swing.JComboBox<String> tipoCocina1;
    private javax.swing.JComboBox<String> tipoCocina2;
    private javax.swing.JLabel tipoCocinaLabel;
    private javax.swing.JLabel tipoCocinaLabel1;
    private javax.swing.JLabel tipoCocinaLabel2;
    private javax.swing.JComboBox<String> tipoDeEvento;
    private javax.swing.JComboBox<String> tipoDeEvento1;
    private javax.swing.JComboBox<String> tipoDeEvento2;
    private javax.swing.JLabel tipoEventoLabel;
    private javax.swing.JLabel tipoEventoLabel1;
    private javax.swing.JLabel tipoEventoLabel2;
    private javax.swing.JPanel tituloPrincipalPanel;
    private javax.swing.JLabel tituloReservaLabel;
    // End of variables declaration//GEN-END:variables
}
